var nmNames = {
'20min.ch - D-CH' : 1,
'Blick Online' : 1,
'Bluewin' : 1,
'Neue Zuercher Zeitung' : 1,
'Neue Zürcher Zeitung' : 1,
'audienzz - NZZ-Netz' : 1,
'NZZ-Netz' : 1,
'tagesanzeiger.ch' : 1,
'Newsnet DCH' : 1,
'Newsnet D-CH' : 1,
'watson.ch' : 1,
'Nordwestschweiz Netz' : 1,
'baslerzeitung.ch' : 1,
'Luzerner Zeitung' : 1,
'luzernerzeitung.ch' : 1,
'srf.ch' : 1,
'St. Galler Tagblatt' : 1,
'zsz.ch' : 1,
'zuonline.ch' : 1,
'Der Landbote' : 1,
'swissmom.ch' : 1,
'familienleben.ch' : 1,
'wireltern.ch' : 1,
'wildeisen.ch' : 1,
'saison.ch' : 1,
'lemenu.ch' : 1,
'tageswoche.ch' : 1,
'telezueri.ch' : 1,
'argovia.ch' : 1,
'radio24.ch' : 1,
'radiopilatus.ch' : 1,
'energy.ch' : 1,
'FM1Today' : 1,
'TeleBaern.tv' : 1,
'TeleM1.ch' : 1,
'tv24.ch' : 1
};
